### ISSUE TITLE
Having issues setting it up

### ISSUE THREAD

**Issue by Ayresia** [BeauAgst/HQT#1]
Can you help, maybe come on discord and help?

**Comment by metacurb** [comment]
Hey @Ayresia , could you possibly explain your issue here? That way if others have the same problem, they'll be able to use the answer from here. Thanks!

**Comment by Ayresia** [comment]
I don't know how to setup this up at all. I don't know how to get the keys and where to put them, can you do an video tutorial or come on share screen discord?

**Comment by metacurb** [comment]
Before you can use this, you'll need to set up your own _Google Custom Search_, and a _Google Custom Search API Key_. That information is found in the readme, and is labelled as "Prerequisites"

All you need to do is go to [Google Custom Search](http://cse.google.com/), and create your own search engine. Make sure you set it to "Search the entire web but emphasize included sites", so that it searches for everything. Under "Details" your Search Engine ID can be found, where there will be a button that reveals it.

Then, you need to get yourself an API key. via the [JSON API](https://developers.google.com/custom-search/json-api/v1/overview). Select or create a project, and generate your key.

Copy both of those int your `.env` file, like so:
```
GOOGLE_KEY=YOUR KEY HERE
GOOGLE_ENGINE_ID=YOUR ID HERE
BEARER_TOKEN=YOUR BEARER TOKEN HERE
```

You'll also need your bearer token, which you will need to intercept from the HQTrivia socket connection.

**Comment by Ayresia** [comment]
What sites do we have to add?

Sites to add?
In The Google Custom Search.

**Comment by metacurb** [comment]
If you enter any url (eg. github.com) afterward, enter the control panel for your new search and change the "sites to search" option and delete the URL you added.

**Comment by Ayresia** [comment]
How can i get the bearer key, can i use an emulator inorder to get it?

**Comment by metacurb** [comment]
You'll need to sniff your network traffic on your mobile device, so that you can intercept data being sent to it. The bearer token is sent from their API once you have opened the app.

**Comment by Ayresia** [comment]
How can i sniff the network traffic with Android 7.0, i know you have to use charlie but is that possible?

**Comment by metacurb** [comment]
As far as I'm aware, you won't be able to use Charlie for Android 7+. But please give it a go and report back!

**Comment by Ayresia** [comment]
What do i have to name the .env and where should i put it

**Comment by metacurb** [comment]
The file should literally be called `.env`, and needs to be in the root of your project.

**Comment by Ayresia** [comment]
There is nothing.

**Comment by Ayresia** [comment]
![image](https://user-images.githubusercontent.com/31165608/41049258-c7f7986c-69b0-11e8-8dbb-accfd2638ab6.png)

The touch.env i created it.

**Comment by metacurb** [comment]
Rename `touch.env` to `.env`

**Comment by Ayresia** [comment]
I cant, i can only rename it to env.env

**Comment by metacurb** [comment]
In your terminal, type `touch .env`, which will create the environment variables file. Inside that place your variables and delete your `touch.env` file.

**Comment by Ayresia** [comment]
Done.
